# app/onboarding_questions.py — 65 вопросов онбординга (fingerprint)
# UI_TYPE: radio | checkbox | slider | dropdown | text_short | text_optional

ONBOARDING_QUESTIONS = [
    # === 1) Кто я по легенде (персонаж) ===
    {"id": 1, "question": "Откуда ты (по вайбу)?", "ui_type": "dropdown", "options": ["СНГ/Восточная Европа", "Европа", "США/Канада", "Латинская Америка", "Азия", "Ближний Восток", "Африка", "Другое"], "default": "США/Канада", "optional": False, "store_to": "background.region_vibe", "other_option": "Другое", "other_placeholder": "Укажите регион"},
    {"id": 2, "question": "Где ты сейчас живешь (без точного адреса)?", "ui_type": "dropdown", "options": ["США", "Канада", "Европа", "СНГ", "Другое"], "default": "США", "optional": False, "store_to": "background.current_region", "other_option": "Другое", "other_placeholder": "Укажите страну/регион"},
    {"id": 3, "question": "Как корректно упоминать локацию публично?", "ui_type": "radio", "options": ["Только страна", "Страна + штат/регион", "Город можно", "Не упоминать вообще"], "default": "Страна + штат/регион", "optional": False, "store_to": "privacy.location_level", "followup_fields": [{"store_to": "privacy.location_state", "label": "Штат/регион", "placeholder": "Например: Калифорния, Техас", "optional": False, "show_when": ["Страна + штат/регион"]}, {"store_to": "privacy.location_city", "label": "Город", "placeholder": "Например: Сан-Франциско, Москва", "optional": False, "show_when": ["Город можно"]}]},
    {"id": 4, "question": "Ты чаще пишешь как «иммигрант/переезд» или это не тема?", "ui_type": "radio", "options": ["Можно упоминать по контексту", "Редко и аккуратно", "Не упоминать"], "default": "Можно упоминать по контексту", "optional": False, "store_to": "background.relocation_mentions", "followup_fields": [{"store_to": "background.relocation_context", "label": "Контекст переезда", "placeholder": "Например: переехал 5 лет назад, из России в США", "optional": False, "show_when": ["Можно упоминать по контексту", "Редко и аккуратно"]}]},
    {"id": 5, "question": "Твоя роль/кто ты по работе? (выбери до 2)", "ui_type": "checkbox", "options": ["Founder", "Executive/Head", "Manager", "Marketer", "Sales", "Engineer/Tech", "Ops/Process", "Creator/Media", "Consultant", "Другое"], "default": ["Manager"], "optional": False, "store_to": "identity.roles", "max_select": 2, "other_option": "Другое", "other_placeholder": "Напишите свою роль"},
    {"id": 6, "question": "В каких темах ты реально силен? (выбери 3)", "ui_type": "checkbox", "options": ["Startups", "AI/Automation", "Marketing/Brand", "Content/Creator", "Sales", "Ops/Processes", "Leadership/Team", "Logistics/Supply chain", "Finance", "Career", "Другое"], "default": ["AI/Automation", "Marketing/Brand", "Ops/Processes"], "optional": False, "store_to": "expertise.topics", "max_select": 3, "other_option": "Другое", "other_placeholder": "Напишите свою тему"},
    {"id": 7, "question": "Можно ли упоминать твой опыт/достижения?", "ui_type": "radio", "options": ["Да, но только если помогает мысли", "Лучше без «я» и регалий", "Вообще не упоминать опыт"], "default": "Да, но только если помогает мысли", "optional": False, "store_to": "style.self_reference_policy", "followup_fields": [{"store_to": "background.experience_details", "label": "Опишите свой опыт/достижения", "placeholder": "Например: 10 лет в маркетинге, ex-Google, запуск 3 стартапов…", "optional": False, "show_when": ["Да, но только если помогает мысли", "Лучше без «я» и регалий"]}]},
    {"id": 8, "question": "Уровень «без понтов» (как говорить про опыт)", "ui_type": "radio", "options": ["Сухо и по делу", "Легко и дружелюбно", "С юмором", "Максимально скромно"], "default": "Сухо и по делу", "optional": False, "store_to": "style.flex_level"},
    {"id": 9, "question": "Можно ли 1 микро-деталь про себя в комменте?", "ui_type": "radio", "options": ["Никогда", "Редко, если в тему", "Можно"], "default": "Редко, если в тему", "optional": False, "store_to": "background.micro_detail_policy"},
    {"id": 10, "question": "Возраст/семья можно упоминать?", "ui_type": "radio", "options": ["Да, по контексту", "Только семья, без возраста", "Лучше не упоминать"], "default": "Да, по контексту", "optional": False, "store_to": "privacy.family_mentions", "followup_fields": [{"store_to": "privacy.age_approx", "label": "Возраст (примерно)", "placeholder": "Например: 30–35, 40+", "optional": False, "show_when": ["Да, по контексту", "Только семья, без возраста"]}, {"store_to": "privacy.family_details", "label": "Семья (кратко)", "placeholder": "Например: женат, 2 детей; не женат; в отношениях", "optional": False, "show_when": ["Да, по контексту", "Только семья, без возраста"]}]},
    {"id": 11, "question": "Хобби/личные детали (чтобы текст был живым) (выбери до 3)", "ui_type": "checkbox", "options": ["Спорт", "Игры", "Музыка", "Семья/дети", "AI-инструменты", "Книги", "Путешествия", "Бизнес/проекты", "Другое"], "default": ["AI-инструменты"], "optional": True, "store_to": "background.human_details", "max_select": 3, "other_option": "Другое", "other_placeholder": "Распишите подробнее"},
    {"id": 12, "question": "Практики/привычки (можно упоминать)?", "ui_type": "checkbox", "options": ["Медитация", "Дыхательные практики", "ЗОЖ", "Терапия (без диагнозов)", "Ничего", "Другое"], "default": ["Ничего"], "optional": True, "store_to": "background.practices", "other_option": "Другое", "other_placeholder": "Распишите подробнее"},
    {"id": 13, "question": "Комьюнити/ивенты (можно упоминать)?", "ui_type": "radio", "options": ["Да, если в тему", "Редко", "Не упоминать"], "default": "Редко", "optional": True, "store_to": "background.community_mentions", "followup_fields": [{"store_to": "background.community_details", "label": "Какие комьюнити/ивенты?", "placeholder": "Например: YC alumni, локальные митапы, конференции", "optional": False, "show_when": ["Да, если в тему", "Редко"]}]},
    {"id": 14, "question": "Опыт из прошлого (можно упоминать только по контексту) (выбери до 3)", "ui_type": "checkbox", "options": ["Крупная корпорация", "Стартапы", "Медиа/продюсирование", "Агентство", "Логистика", "Свой бизнес", "Другое", "Не упоминать"], "default": ["Не упоминать"], "optional": True, "store_to": "background.past_experience_tags", "max_select": 3, "other_option": "Другое", "other_placeholder": "Напишите свой опыт", "exclusive_option": "Не упоминать", "followup_fields": [{"store_to": "background.past_experience_details", "label": "Расшифруйте", "placeholder": "Например: 5 лет в McKinsey, потом 2 стартапа", "optional": True, "show_when": ["Крупная корпорация", "Стартапы", "Медиа/продюсирование", "Агентство", "Логистика", "Свой бизнес", "Другое"]}]},
    {"id": 15, "question": "Якоря опыта по контекстам (выбери до 3)", "ui_type": "checkbox", "options": ["AI/automation", "Content/blogging", "Logistics", "Team/management", "Sales/negotiation", "Ops/process", "Другое"], "default": ["AI/automation"], "optional": True, "store_to": "background.context_anchors", "max_select": 3, "other_option": "Другое", "other_placeholder": "Напишите свой контекст", "followup_fields": [{"store_to": "background.context_anchors_examples", "label": "Примеры", "placeholder": "Например: внедрял ChatGPT в 50+ процессах, вел блог 3 года", "optional": True}]},
    # === 2) Общий тон ===
    {"id": 16, "question": "Тон по умолчанию", "ui_type": "radio", "options": ["Дружелюбный", "Нейтрально-профи", "Жестко и по делу", "Поддерживающе", "С иронией"], "default": "Дружелюбный", "optional": False, "store_to": "style.tone_default"},
    {"id": 17, "question": "Какой «температуры» общение?", "ui_type": "radio", "options": ["Спокойно и без напряга", "Энергично", "Сдержанно", "Чуть провокационно"], "default": "Спокойно и без напряга", "optional": False, "store_to": "style.energy"},
    {"id": 18, "question": "Ритм предложений", "ui_type": "radio", "options": ["Короткие", "Средние", "Смешанный"], "default": "Смешанный", "optional": False, "store_to": "style.sentence_style"},
    {"id": 19, "question": "Прямота 1–10", "ui_type": "slider", "options": [1, 10], "default": 5, "optional": False, "store_to": "style.directness", "slider_labels": {"min": "Мягко, осторожно", "max": "Прямо, жёстко"}},
    {"id": 20, "question": "Если человек «тупит», как отвечаешь?", "ui_type": "radio", "options": ["Спокойно объясняю", "Чуть подколю", "Игнор/ухожу", "Жестче, но без хамства"], "default": "Спокойно объясняю", "optional": False, "store_to": "style.handling_stupid"},
    {"id": 21, "question": "Юмор", "ui_type": "radio", "options": ["Нет", "Легкий", "Сарказм", "Мемно (аккуратно)"], "default": "Легкий", "optional": False, "store_to": "style.humor_type"},
    {"id": 22, "question": "Как обычно начинаешь комментарий?", "ui_type": "radio", "options": ["Сразу с конкретики из поста", "С короткой реакцией + конкретика", "С вопроса", "С контрпоинта"], "default": "Сразу с конкретики из поста", "optional": False, "store_to": "style.opening_pattern"},
    {"id": 23, "question": "Выбери 2 стартовых шаблона (для «живого» голоса)", "ui_type": "checkbox", "options": ["Сильная мысль. Особенно про …", "Спорно. Потому что …", "Я бы добавил вот что …", "Вот где обычно ломается …", "Смешно, но правда: …", "Вопрос: …", "Другое"], "default": ["Я бы добавил вот что …", "Вопрос: …"], "optional": True, "store_to": "style.starters_selected", "max_select": 2, "other_option": "Другое", "other_placeholder": "Напишите свой шаблон"},
    # === 3) Что я никогда не делаю ===
    {"id": 24, "question": "Запрещенные темы (выбери)", "ui_type": "checkbox", "options": ["Политика", "Религия", "Раса/этничность", "Диагнозы/психотерапия", "Секс", "Болезни (тяжелые)", "Другое"], "default": ["Политика", "Религия", "Раса/этничность"], "optional": False, "store_to": "safety.taboo_topics", "other_option": "Другое", "other_placeholder": "Напишите тему"},
    {"id": 25, "question": "Запахи текста, которые бесишься видеть (выбери до 4)", "ui_type": "checkbox", "options": ["Канцелярит", "Пафос/гуру", "Мотивационные клише", "Слишком вежливо и пусто", "Слишком умничаю", "Слишком нейтрально", "Много воды", "Другое"], "default": ["Канцелярит", "Мотивационные клише"], "optional": False, "store_to": "anti_ai.hated_smells", "max_select": 4, "other_option": "Другое", "other_placeholder": "Опишите свой вариант"},
    {"id": 26, "question": "Темы, которые точно не трогаешь", "ui_type": "checkbox", "options": ["Политика", "Религия", "Расизм", "Война", "Теории заговора", "Другое", "Нет"], "default": ["Политика", "Религия", "Расизм"], "optional": False, "store_to": "safety.never_topics", "other_option": "Другое", "other_placeholder": "Напишите тему", "exclusive_option": "Нет"},
    {"id": 27, "question": "Если тебя тянут в психотерапию/диагнозы, что делаем?", "ui_type": "radio", "options": ["Ухожу от темы мягко", "Говорю «не моя зона» и возвращаю к практике", "Игнорирую"], "default": "Говорю «не моя зона» и возвращаю к практике", "optional": False, "store_to": "safety.therapy_handling"},
    {"id": 28, "question": "Бизнес-английский/жаргон", "ui_type": "radio", "options": ["Можно", "Умеренно", "Лучше проще словами", "Нельзя"], "default": "Умеренно", "optional": False, "store_to": "style.jargon_level"},
    {"id": 29, "question": "В каких случаях можно упоминать статус/титулы?", "ui_type": "radio", "options": ["Только если напрямую усиливает мысль", "Можно иногда", "Не упоминать"], "default": "Только если напрямую усиливает мысль", "optional": False, "store_to": "style.status_mentions", "followup_fields": [{"store_to": "identity.titles_optional", "label": "Ваши титулы/статус (если хотите указать)", "placeholder": "Например: ex-Google, Founder, Head of Growth", "optional": True, "show_when": ["Только если напрямую усиливает мысль", "Можно иногда"]}]},
    {"id": 30, "question": "Запрещенные «общие ответы»", "ui_type": "checkbox", "options": ["It depends", "Great post", "Love this", "So true", "Важно отметить", "В конечном итоге", "Тут все просто", "Другое"], "default": ["Great post", "Love this", "So true", "Важно отметить", "В конечном итоге"], "optional": False, "store_to": "anti_ai.banned_phrases", "other_option": "Другое", "other_placeholder": "Напишите фразу"},
    # === 4) Структура типичного ответа ===
    {"id": 31, "question": "Задача твоих комментариев чаще какая?", "ui_type": "radio", "options": ["Получить ответ автора", "Показать экспертность", "Поддержать", "Поспорить", "Увести в диалог/DM"], "default": "Получить ответ автора", "optional": False, "store_to": "interaction.comment_goal"},
    {"id": 32, "question": "Сколько абзацев обычно в комментарии?", "ui_type": "radio", "options": ["1", "1–2", "2–3", "Не важно"], "default": "1–2", "optional": False, "store_to": "style.paragraph_pref"},
    {"id": 33, "question": "Стандартный порядок мысли", "ui_type": "radio", "options": ["Якорь из поста → мысль → вопрос", "Реакция → якорь → мысль → вопрос", "Контрпоинт → объяснение → вопрос", "Совет → почему → вопрос"], "default": "Якорь из поста → мысль → вопрос", "optional": False, "store_to": "style.structure_pref"},
    {"id": 34, "question": "Как подхватываешь эмоцию автора?", "ui_type": "radio", "options": ["Зеркалю тон (спокойно/сарказм)", "Всегда спокойно", "Всегда бодро", "Чуть подколю"], "default": "Зеркалю тон (спокойно/сарказм)", "optional": False, "store_to": "style.empathy_mode"},
    {"id": 35, "question": "Как добавляешь опыт?", "ui_type": "radio", "options": ["Только 1 короткая вставка максимум", "Можно 1–2 фразы", "Лучше вообще без опыта"], "default": "Только 1 короткая вставка максимум", "optional": False, "store_to": "style.experience_injection"},
    {"id": 36, "question": "Что для тебя «конкретная мысль»?", "ui_type": "radio", "options": ["1 тезис", "1 тезис + пример", "1 тезис + шаг что делать", "Не важно"], "default": "1 тезис + шаг что делать", "optional": False, "store_to": "style.what_is_point"},
    {"id": 37, "question": "Вопрос в конце?", "ui_type": "radio", "options": ["Почти всегда", "Иногда", "Редко", "Никогда"], "default": "Почти всегда", "optional": False, "store_to": "style.end_question_preference"},
    # === 5) Темы: логистика ===
    {"id": 38, "question": "Как объясняешь сложное?", "ui_type": "radio", "options": ["Очень просто, без терминов", "Просто, но с 1–2 терминами", "Можно технично"], "default": "Просто, но с 1–2 терминами", "optional": False, "store_to": "domain.logistics.explain_style"},
    {"id": 39, "question": "Термины в тексте", "ui_type": "radio", "options": ["Избегаю", "Умеренно", "Можно много"], "default": "Умеренно", "optional": False, "store_to": "style.term_level"},
    {"id": 40, "question": "Фразы, которые звучат именно как ты", "ui_type": "text_optional", "options": [], "default": "Напишите снизу свои фразы", "optional": True, "store_to": "style.signature_phrases"},
    {"id": 41, "question": "Образная мини-зарисовка (1–2 предложения)", "ui_type": "text_optional", "options": [], "default": "", "optional": True, "store_to": "domain.logistics.imagery_optional"},
    # === 6) Темы: AI ===
    {"id": 42, "question": "Позиция про AI (выбери ближе всего)", "ui_type": "radio", "options": ["AI работает, если внедрять правильно", "AI в основном хайп", "AI меняет всё прямо сейчас", "Скептик: полезно точечно"], "default": "AI работает, если внедрять правильно", "optional": False, "store_to": "domain.ai.position"},
    {"id": 43, "question": "Тезисы про AI (выбери до 3)", "ui_type": "checkbox", "options": ["Технология останется", "Пузырь частично сдуется", "Данные решают", "Интеграция важнее модели", "Процессы важнее инструментов", "Другое"], "default": ["Технология останется", "Процессы важнее инструментов"], "optional": False, "store_to": "domain.ai.theses", "max_select": 3, "other_option": "Другое", "other_placeholder": "Напишите свой тезис"},
    {"id": 44, "question": "1–2 фирменные формулировки", "ui_type": "text_optional", "options": [], "default": "", "optional": True, "store_to": "domain.ai.signature_lines_optional"},
    # === 7) Темы: стартапы/карьера ===
    {"id": 45, "question": "Тезисы про стартап-жизнь (выбери до 2)", "ui_type": "checkbox", "options": ["Без глянца, тяжело", "Итерации решают", "Продажи важнее продукта", "Команда ломает/строит", "Фокус важнее идей", "Другое"], "default": ["Итерации решают"], "optional": True, "store_to": "domain.startups.theses", "max_select": 2, "other_option": "Другое", "other_placeholder": "Напишите свой тезис", "followup_fields": [{"store_to": "domain.startups.details", "label": "Дополнительно про стартапы", "placeholder": "Ваш опыт, кейсы, выводы", "optional": True}]},
    {"id": 46, "question": "Про работу и границы", "ui_type": "radio", "options": ["Я много работаю", "Я за баланс", "Я за результат, но без выгорания", "Зависит от этапа"], "default": "Я за результат, но без выгорания", "optional": True, "store_to": "domain.career.boundaries"},
    # === 8) Юмор и интонация ===
    {"id": 47, "question": "Уровень юмора 1–10", "ui_type": "slider", "options": [1, 10], "default": 4, "optional": False, "store_to": "style.humor_level", "slider_labels": {"min": "Почти без юмора", "max": "Много юмора"}},
    {"id": 48, "question": "На что нельзя шутить?", "ui_type": "checkbox", "options": ["Болезни/недуги", "Религия", "Политика", "Раса/этничность", "Внешность", "Другое", "Нет ограничений"], "default": ["Болезни/недуги", "Религия", "Политика", "Раса/этничность"], "optional": False, "store_to": "safety.humor_taboo", "other_option": "Другое", "other_placeholder": "Напишите тему", "exclusive_option": "Нет ограничений"},
    {"id": 49, "question": "Юмор чаще про…", "ui_type": "radio", "options": ["Самоирония", "Над индустрией", "Над жизнью", "Саркастичный подкол", "Почти не шучу"], "default": "Над индустрией", "optional": False, "store_to": "style.humor_target"},
    {"id": 50, "question": "1 пример шутки/подкола", "ui_type": "text_optional", "options": [], "default": "", "optional": True, "store_to": "style.joke_example_optional"},
    # === 9) Жизненные вопросы ===
    {"id": 51, "question": "«Одна правда про жизнь» (выбери)", "ui_type": "radio", "options": ["Надо развиваться", "Дисциплина важнее мотивации", "Люди решают", "Здоровье решает", "Свобода через ответственность"], "default": "Дисциплина важнее мотивации", "optional": True, "store_to": "worldview.life_truth"},
    {"id": 52, "question": "«Doing well in life» для тебя это…", "ui_type": "checkbox", "options": ["Свобода по времени", "Деньги", "Семья", "Здоровье", "Интерес к жизни", "Влияние/польза", "Другое"], "default": ["Свобода по времени", "Семья"], "optional": True, "store_to": "worldview.doing_well", "other_option": "Другое", "other_placeholder": "Распишите подробнее", "followup_fields": [{"store_to": "worldview.doing_well_other", "label": "Что ещё важно?", "placeholder": "Свои формулировки", "optional": True}]},
    {"id": 53, "question": "Дружба/отношения и границы", "ui_type": "radio", "options": ["Я за близкий круг", "Я про «партнерство», не дружбу", "Я легко схожусь", "Не хочу об этом писать"], "default": "Я за близкий круг", "optional": True, "store_to": "worldview.relationships"},
    {"id": 54, "question": "Напиши 1 пример, как ты отвечаешь на личный вопрос (1–2 предложения)", "ui_type": "text_optional", "options": [], "default": "Например: «Да, у меня двое детей — это сильно меняет приоритеты»", "optional": True, "store_to": "worldview.short_answer_optional"},
    # === 10) Как отвечаю в спорах ===
    {"id": 55, "question": "Если спор накаляется, ты…", "ui_type": "radio", "options": ["Снижаю тон и уточняю факты", "Шучу и снимаю напряжение", "Завершаю диалог", "Отвечаю жестче"], "default": "Снижаю тон и уточняю факты", "optional": False, "store_to": "debate.deescalation"},
    {"id": 56, "question": "«Согласен и добавлю» (выбери 2 шаблона)", "ui_type": "checkbox", "options": ["Да, и вот что важно…", "Согласен, но есть нюанс…", "Верно. Я бы добавил…", "100%. Плюс…", "Суть та же, но…", "Другое"], "default": ["Согласен, но есть нюанс…", "Верно. Я бы добавил…"], "optional": True, "store_to": "debate.agree_add_templates", "max_select": 2, "other_option": "Другое", "other_placeholder": "Напишите свой шаблон"},
    {"id": 57, "question": "Ты чаще споришь про…", "ui_type": "radio", "options": ["AI", "Startups", "Маркетинг", "Операционка/процессы", "Логистика", "Редко спорю", "Другое"], "default": "AI", "optional": False, "store_to": "debate.common_topic", "other_option": "Другое", "other_placeholder": "Напишите, о чём именно"},
    {"id": 58, "question": "Тип аргумента в споре", "ui_type": "radio", "options": ["Факты/цифры", "Практика/кейсы", "Логика/причина-следствие", "Вопросами довожу до мысли"], "default": "Логика/причина-следствие", "optional": False, "store_to": "debate.argument_style"},
    # === 11) Палитра фраз ===
    {"id": 59, "question": "Выбери 5 «кирпичиков» (готовые блоки)", "ui_type": "checkbox", "options": ["Смотри, тут ключевое…", "Если по-честному…", "По факту…", "Тут не в … проблема, а в …", "Проверяется быстро: …", "Это решается процессом/системой", "Давай проще: …", "Вопрос: …", "Я бы сделал так: …", "Согласен, но есть нюанс…", "Другое"], "default": ["Смотри, тут ключевое…", "По факту…", "Вопрос: …", "Давай проще: …", "Это решается процессом/системой"], "optional": True, "store_to": "style.bricks_selected", "max_select": 5, "other_option": "Другое", "other_placeholder": "Напишите свою фразу"},
    {"id": 60, "question": "Запрещенные фразы (выбери до 5)", "ui_type": "checkbox", "options": ["Great post", "Love this", "So true", "Важно отметить", "В конечном итоге", "In today's world", "Let's unpack", "Во-первых/во-вторых", "Другое"], "default": ["Great post", "Love this", "Важно отметить", "В конечном итоге", "Let's unpack"], "optional": True, "store_to": "anti_ai.banned_phrases_extra", "max_select": 5, "other_option": "Другое", "other_placeholder": "Напишите фразу"},
    # === 12) Как взаимодействую с людьми ===
    {"id": 61, "question": "Когда человеку тяжело, ты…", "ui_type": "radio", "options": ["Слушаю и даю короткий совет", "Поддерживаю без советов", "Даю практический шаг", "Не комментирую такие темы"], "default": "Даю практический шаг", "optional": False, "store_to": "interaction.support_style"},
    {"id": 62, "question": "Как не обесцениваешь?", "ui_type": "radio", "options": ["Признаю сложность и даю шаг", "Подчеркиваю прогресс", "Говорю прямо, но уважительно"], "default": "Признаю сложность и даю шаг", "optional": False, "store_to": "interaction.validation_style"},
    {"id": 63, "question": "Как ты мягко не соглашаешься и добавляешь нюанс?", "ui_type": "radio", "options": ["Вопросом", "Контрпримером", "Нюансом", "Мини-советом"], "default": "Вопросом", "optional": False, "store_to": "interaction.challenge_style"},
    {"id": 64, "question": "Ответ на токсичную формулировку (выбери стратегию)", "ui_type": "radio", "options": ["Перевожу в факты", "Ставлю границу и выхожу", "Спокойно обозначаю неприемлемость", "Игнор"], "default": "Спокойно обозначаю неприемлемость", "optional": False, "store_to": "safety.toxic_handling"},
    # === 13) Резюме и обязательные правила ===
    {"id": 65, "question": "5 обязательных правил твоего текста (выбери 5)", "ui_type": "checkbox", "options": ["Всегда 1 конкретика из поста", "Одна мысль, без воды", "Без канцелярита", "Без мотивационных клише", "В конце вопрос (если уместно)", "Без выдуманного личного опыта", "Дружелюбно, но по делу", "Можно легкий сарказм, без токсичности", "Не трогать табу-темы"], "default": ["Всегда 1 конкретика из поста", "Одна мысль, без воды", "Без канцелярита", "Без выдуманного личного опыта", "Не трогать табу-темы"], "optional": False, "store_to": "rules.mandatory", "max_select": 5},
]

# Группировка по секциям для UI
ONBOARDING_SECTIONS = [
    {"title": "1) Кто я по легенде (персонаж)", "ids": list(range(1, 16))},
    {"title": "2) Общий тон: как я говорю", "ids": list(range(16, 24))},
    {"title": "3) Что я никогда не делаю", "ids": list(range(24, 31))},
    {"title": "4) Структура типичного ответа", "ids": list(range(31, 38))},
    {"title": "5) Темы", "ids": list(range(38, 42))},
    {"title": "6) Темы", "ids": list(range(42, 45))},
    {"title": "7) Темы: стартапы/карьера/взрослость", "ids": list(range(45, 47))},
    {"title": "8) Юмор", "ids": list(range(47, 51))},
    {"title": "9) Жизненные вопросы (личные)", "ids": list(range(51, 55))},
    {"title": "10) Как отвечаю в спорах", "ids": list(range(55, 59))},
    {"title": "11) Палитра фраз (строительные блоки)", "ids": list(range(59, 61))},
    {"title": "12) Как взаимодействую с людьми", "ids": list(range(61, 65))},
    {"title": "13) Резюме и обязательные правила", "ids": [65]},
]

QUESTIONS_BY_ID = {q["id"]: q for q in ONBOARDING_QUESTIONS}


def get_sections_with_questions():
    """Возвращает секции с вложенными вопросами."""
    sections = []
    for sec in ONBOARDING_SECTIONS:
        questions = [QUESTIONS_BY_ID[i] for i in sec["ids"] if i in QUESTIONS_BY_ID]
        sections.append({"title": sec["title"], "questions": questions})
    return sections


def get_all_questions_flat(locale: str = "ru"):
    """Плоский список всех вопросов (63 + extra) с section_title для пошагового UI.
    locale: 'ru' | 'en' — язык вопросов и ответов."""
    if locale == "en":
        sections = ONBOARDING_SECTIONS_EN
        questions_by_id = QUESTIONS_BY_ID_EN
        extra = EXTRA_QUESTIONS_EN
        extra_section = "Additional"
    else:
        sections = ONBOARDING_SECTIONS
        questions_by_id = QUESTIONS_BY_ID
        extra = EXTRA_QUESTIONS
        extra_section = "Дополнительно"
    result = []
    for sec in sections:
        for i in sec["ids"]:
            if i in questions_by_id:
                q = dict(questions_by_id[i])
                q["section_title"] = sec["title"]
                result.append(q)
    for eq in extra:
        q = dict(eq)
        q["section_title"] = extra_section
        result.append(q)
    return result


# Дополнительные (для продукта)
EXTRA_QUESTIONS = [
    {"id": "roughness", "question": "Anti-AI «шероховатость» 1–10", "ui_type": "slider", "options": [1, 10], "default": 6, "optional": False, "store_to": "anti_ai.roughness", "slider_labels": {"min": "Гладкий, отполированный", "max": "Живой, как человек"}},
]

# === English translations for interview (locale=en) ===
ONBOARDING_SECTIONS_EN = [
    {"title": "1) Who I am (persona)", "ids": list(range(1, 16))},
    {"title": "2) General tone: how I speak", "ids": list(range(16, 24))},
    {"title": "3) What I never do", "ids": list(range(24, 31))},
    {"title": "4) Typical response structure", "ids": list(range(31, 38))},
    {"title": "5) Topics", "ids": list(range(38, 42))},
    {"title": "6) Topics", "ids": list(range(42, 45))},
    {"title": "7) Topics: startups/career", "ids": list(range(45, 47))},
    {"title": "8) Humor", "ids": list(range(47, 51))},
    {"title": "9) Life questions (personal)", "ids": list(range(51, 55))},
    {"title": "10) How I respond in debates", "ids": list(range(55, 59))},
    {"title": "11) Phrase palette (building blocks)", "ids": list(range(59, 61))},
    {"title": "12) How I interact with people", "ids": list(range(61, 65))},
    {"title": "13) Summary and mandatory rules", "ids": [65]},
]

ONBOARDING_QUESTIONS_EN = [
    {"id": 1, "question": "Where are you from (by vibe)?", "ui_type": "dropdown", "options": ["CIS/Eastern Europe", "Europe", "USA/Canada", "Latin America", "Asia", "Middle East", "Africa", "Other"], "default": "USA/Canada", "optional": False, "store_to": "background.region_vibe", "other_option": "Other", "other_placeholder": "Specify region"},
    {"id": 2, "question": "Where do you live now (no exact address)?", "ui_type": "dropdown", "options": ["USA", "Canada", "Europe", "CIS", "Other"], "default": "USA", "optional": False, "store_to": "background.current_region", "other_option": "Other", "other_placeholder": "Specify country/region"},
    {"id": 3, "question": "How to mention location publicly?", "ui_type": "radio", "options": ["Country only", "Country + state/region", "City is OK", "Don't mention at all"], "default": "Country + state/region", "optional": False, "store_to": "privacy.location_level", "followup_fields": [{"store_to": "privacy.location_state", "label": "State/region", "placeholder": "e.g. California, Texas", "optional": False, "show_when": ["Country + state/region"]}, {"store_to": "privacy.location_city", "label": "City", "placeholder": "e.g. San Francisco, Moscow", "optional": False, "show_when": ["City is OK"]}]},
    {"id": 4, "question": "Do you write as «immigrant/relocation» or is that not a topic?", "ui_type": "radio", "options": ["Can mention when relevant", "Rarely and carefully", "Don't mention"], "default": "Can mention when relevant", "optional": False, "store_to": "background.relocation_mentions", "followup_fields": [{"store_to": "background.relocation_context", "label": "Relocation context", "placeholder": "e.g. moved 5 years ago, from Russia to USA", "optional": False, "show_when": ["Can mention when relevant", "Rarely and carefully"]}]},
    {"id": 5, "question": "Your role / who you are at work? (select up to 2)", "ui_type": "checkbox", "options": ["Founder", "Executive/Head", "Manager", "Marketer", "Sales", "Engineer/Tech", "Ops/Process", "Creator/Media", "Consultant", "Other"], "default": ["Manager"], "optional": False, "store_to": "identity.roles", "max_select": 2, "other_option": "Other", "other_placeholder": "Write your role"},
    {"id": 6, "question": "What topics are you strong in? (select 3)", "ui_type": "checkbox", "options": ["Startups", "AI/Automation", "Marketing/Brand", "Content/Creator", "Sales", "Ops/Processes", "Leadership/Team", "Logistics/Supply chain", "Finance", "Career", "Other"], "default": ["AI/Automation", "Marketing/Brand", "Ops/Processes"], "optional": False, "store_to": "expertise.topics", "max_select": 3, "other_option": "Other", "other_placeholder": "Write your topic"},
    {"id": 7, "question": "Can your experience/achievements be mentioned?", "ui_type": "radio", "options": ["Yes, but only if it helps the point", "Better without «I» and credentials", "Don't mention experience at all"], "default": "Yes, but only if it helps the point", "optional": False, "store_to": "style.self_reference_policy", "followup_fields": [{"store_to": "background.experience_details", "label": "Describe your experience/achievements", "placeholder": "e.g. 10 years in marketing, ex-Google, 3 startups launched…", "optional": False, "show_when": ["Yes, but only if it helps the point", "Better without «I» and credentials"]}]},
    {"id": 8, "question": "«No flex» level (how to talk about experience)", "ui_type": "radio", "options": ["Dry and to the point", "Light and friendly", "With humor", "Very modest"], "default": "Dry and to the point", "optional": False, "store_to": "style.flex_level"},
    {"id": 9, "question": "Can you add 1 micro-detail about yourself in a comment?", "ui_type": "radio", "options": ["Never", "Rarely, if relevant", "Yes"], "default": "Rarely, if relevant", "optional": False, "store_to": "background.micro_detail_policy"},
    {"id": 10, "question": "Can age/family be mentioned?", "ui_type": "radio", "options": ["Yes, when relevant", "Family only, no age", "Better not mention"], "default": "Yes, when relevant", "optional": False, "store_to": "privacy.family_mentions", "followup_fields": [{"store_to": "privacy.age_approx", "label": "Age (approx)", "placeholder": "e.g. 30–35, 40+", "optional": False, "show_when": ["Yes, when relevant", "Family only, no age"]}, {"store_to": "privacy.family_details", "label": "Family (brief)", "placeholder": "e.g. married, 2 kids; single; in a relationship", "optional": False, "show_when": ["Yes, when relevant", "Family only, no age"]}]},
    {"id": 11, "question": "Hobbies/personal details (to make text alive) (select up to 3)", "ui_type": "checkbox", "options": ["Sports", "Gaming", "Music", "Family/kids", "AI tools", "Books", "Travel", "Business/projects", "Other"], "default": ["AI tools"], "optional": True, "store_to": "background.human_details", "max_select": 3, "other_option": "Other", "other_placeholder": "Elaborate"},
    {"id": 12, "question": "Practices/habits (can mention)?", "ui_type": "checkbox", "options": ["Meditation", "Breathing practices", "Healthy lifestyle", "Therapy (no diagnoses)", "Nothing", "Other"], "default": ["Nothing"], "optional": True, "store_to": "background.practices", "other_option": "Other", "other_placeholder": "Elaborate"},
    {"id": 13, "question": "Community/events (can mention)?", "ui_type": "radio", "options": ["Yes, if relevant", "Rarely", "Don't mention"], "default": "Rarely", "optional": True, "store_to": "background.community_mentions", "followup_fields": [{"store_to": "background.community_details", "label": "Which communities/events?", "placeholder": "e.g. YC alumni, local meetups, conferences", "optional": False, "show_when": ["Yes, if relevant", "Rarely"]}]},
    {"id": 14, "question": "Past experience (mention only when relevant) (select up to 3)", "ui_type": "checkbox", "options": ["Large corporation", "Startups", "Media/production", "Agency", "Logistics", "Own business", "Other", "Don't mention"], "default": ["Don't mention"], "optional": True, "store_to": "background.past_experience_tags", "max_select": 3, "other_option": "Other", "other_placeholder": "Write your experience", "exclusive_option": "Don't mention", "followup_fields": [{"store_to": "background.past_experience_details", "label": "Elaborate", "placeholder": "e.g. 5 years at McKinsey, then 2 startups", "optional": True, "show_when": ["Large corporation", "Startups", "Media/production", "Agency", "Logistics", "Own business", "Other"]}]},
    {"id": 15, "question": "Experience anchors by context (select up to 3)", "ui_type": "checkbox", "options": ["AI/automation", "Content/blogging", "Logistics", "Team/management", "Sales/negotiation", "Ops/process", "Other"], "default": ["AI/automation"], "optional": True, "store_to": "background.context_anchors", "max_select": 3, "other_option": "Other", "other_placeholder": "Write your context", "followup_fields": [{"store_to": "background.context_anchors_examples", "label": "Examples", "placeholder": "e.g. deployed ChatGPT in 50+ processes, ran blog 3 years", "optional": True}]},
    {"id": 16, "question": "Default tone", "ui_type": "radio", "options": ["Friendly", "Neutral-professional", "Direct and to the point", "Supportive", "With irony"], "default": "Friendly", "optional": False, "store_to": "style.tone_default"},
    {"id": 17, "question": "What «temperature» is your communication?", "ui_type": "radio", "options": ["Calm and relaxed", "Energetic", "Reserved", "Slightly provocative"], "default": "Calm and relaxed", "optional": False, "store_to": "style.energy"},
    {"id": 18, "question": "Sentence rhythm", "ui_type": "radio", "options": ["Short", "Medium", "Mixed"], "default": "Mixed", "optional": False, "store_to": "style.sentence_style"},
    {"id": 19, "question": "Directness 1–10", "ui_type": "slider", "options": [1, 10], "default": 5, "optional": False, "store_to": "style.directness", "slider_labels": {"min": "Soft, careful", "max": "Direct, firm"}},
    {"id": 20, "question": "When someone «doesn't get it», how do you respond?", "ui_type": "radio", "options": ["Calmly explain", "Light tease", "Ignore/leave", "Firmer, but no rudeness"], "default": "Calmly explain", "optional": False, "store_to": "style.handling_stupid"},
    {"id": 21, "question": "Humor", "ui_type": "radio", "options": ["None", "Light", "Sarcasm", "Memes (carefully)"], "default": "Light", "optional": False, "store_to": "style.humor_type"},
    {"id": 22, "question": "How do you usually start a comment?", "ui_type": "radio", "options": ["Straight to specifics from the post", "Short reaction + specifics", "With a question", "With a counterpoint"], "default": "Straight to specifics from the post", "optional": False, "store_to": "style.opening_pattern"},
    {"id": 23, "question": "Select 2 opening templates (for «live» voice)", "ui_type": "checkbox", "options": ["Strong point. Especially about …", "Controversial. Because …", "I'd add this …", "Here's where it usually breaks …", "Funny but true: …", "Question: …", "Other"], "default": ["I'd add this …", "Question: …"], "optional": True, "store_to": "style.starters_selected", "max_select": 2, "other_option": "Other", "other_placeholder": "Write your template"},
    {"id": 24, "question": "Taboo topics (select)", "ui_type": "checkbox", "options": ["Politics", "Religion", "Race/ethnicity", "Diagnoses/therapy", "Sex", "Serious illness", "Other"], "default": ["Politics", "Religion", "Race/ethnicity"], "optional": False, "store_to": "safety.taboo_topics", "other_option": "Other", "other_placeholder": "Write topic"},
    {"id": 25, "question": "Text «smells» you hate to see (select up to 4)", "ui_type": "checkbox", "options": ["Corporate speak", "Guru/pomp", "Motivational clichés", "Too polite and empty", "Too smart", "Too neutral", "Too much fluff", "Other"], "default": ["Corporate speak", "Motivational clichés"], "optional": False, "store_to": "anti_ai.hated_smells", "max_select": 4, "other_option": "Other", "other_placeholder": "Describe your variant"},
    {"id": 26, "question": "Topics you never touch", "ui_type": "checkbox", "options": ["Politics", "Religion", "Racism", "War", "Conspiracy theories", "Other", "None"], "default": ["Politics", "Religion", "Racism"], "optional": False, "store_to": "safety.never_topics", "other_option": "Other", "other_placeholder": "Write topic", "exclusive_option": "None"},
    {"id": 27, "question": "When pulled into therapy/diagnoses, what do we do?", "ui_type": "radio", "options": ["Gently steer away", "Say «not my zone» and return to practice", "Ignore"], "default": "Say «not my zone» and return to practice", "optional": False, "store_to": "safety.therapy_handling"},
    {"id": 28, "question": "Business English/jargon", "ui_type": "radio", "options": ["OK", "Moderate", "Prefer simpler words", "No"], "default": "Moderate", "optional": False, "store_to": "style.jargon_level"},
    {"id": 29, "question": "When can status/titles be mentioned?", "ui_type": "radio", "options": ["Only if it directly strengthens the point", "Sometimes OK", "Don't mention"], "default": "Only if it directly strengthens the point", "optional": False, "store_to": "style.status_mentions", "followup_fields": [{"store_to": "identity.titles_optional", "label": "Your titles/status (if you want to specify)", "placeholder": "e.g. ex-Google, Founder, Head of Growth", "optional": True, "show_when": ["Only if it directly strengthens the point", "Sometimes OK"]}]},
    {"id": 30, "question": "Banned «generic replies»", "ui_type": "checkbox", "options": ["It depends", "Great post", "Love this", "So true", "It's worth noting", "In the end", "It's simple", "Other"], "default": ["Great post", "Love this", "So true", "It's worth noting", "In the end"], "optional": False, "store_to": "anti_ai.banned_phrases", "other_option": "Other", "other_placeholder": "Write phrase"},
    {"id": 31, "question": "What's the main goal of your comments?", "ui_type": "radio", "options": ["Get author's reply", "Show expertise", "Support", "Argue", "Move to DM/dialogue"], "default": "Get author's reply", "optional": False, "store_to": "interaction.comment_goal"},
    {"id": 32, "question": "How many paragraphs usually in a comment?", "ui_type": "radio", "options": ["1", "1–2", "2–3", "Doesn't matter"], "default": "1–2", "optional": False, "store_to": "style.paragraph_pref"},
    {"id": 33, "question": "Standard thought order", "ui_type": "radio", "options": ["Anchor from post → point → question", "Reaction → anchor → point → question", "Counterpoint → explanation → question", "Advice → why → question"], "default": "Anchor from post → point → question", "optional": False, "store_to": "style.structure_pref"},
    {"id": 34, "question": "How do you mirror author's emotion?", "ui_type": "radio", "options": ["Mirror tone (calm/sarcasm)", "Always calm", "Always upbeat", "Light tease"], "default": "Mirror tone (calm/sarcasm)", "optional": False, "store_to": "style.empathy_mode"},
    {"id": 35, "question": "How do you add experience?", "ui_type": "radio", "options": ["Only 1 short insert max", "1–2 phrases OK", "Better without experience"], "default": "Only 1 short insert max", "optional": False, "store_to": "style.experience_injection"},
    {"id": 36, "question": "What's a «concrete point» for you?", "ui_type": "radio", "options": ["1 thesis", "1 thesis + example", "1 thesis + action step", "Doesn't matter"], "default": "1 thesis + action step", "optional": False, "store_to": "style.what_is_point"},
    {"id": 37, "question": "Question at the end?", "ui_type": "radio", "options": ["Almost always", "Sometimes", "Rarely", "Never"], "default": "Almost always", "optional": False, "store_to": "style.end_question_preference"},
    {"id": 38, "question": "How do you explain complex things?", "ui_type": "radio", "options": ["Very simple, no terms", "Simple but with 1–2 terms", "Technical OK"], "default": "Simple but with 1–2 terms", "optional": False, "store_to": "domain.logistics.explain_style"},
    {"id": 39, "question": "Terms in text", "ui_type": "radio", "options": ["Avoid", "Moderate", "Many OK"], "default": "Moderate", "optional": False, "store_to": "style.term_level"},
    {"id": 40, "question": "Phrases that sound like you", "ui_type": "text_optional", "options": [], "default": "Write your phrases below", "optional": True, "store_to": "style.signature_phrases"},
    {"id": 41, "question": "Imagery mini-sketch (1–2 sentences)", "ui_type": "text_optional", "options": [], "default": "", "optional": True, "store_to": "domain.logistics.imagery_optional"},
    {"id": 42, "question": "Position on AI (select closest)", "ui_type": "radio", "options": ["AI works if implemented right", "AI is mostly hype", "AI changes everything now", "Skeptic: useful in spots"], "default": "AI works if implemented right", "optional": False, "store_to": "domain.ai.position"},
    {"id": 43, "question": "AI theses (select up to 3)", "ui_type": "checkbox", "options": ["Tech will stay", "Bubble will partly deflate", "Data wins", "Integration matters more than model", "Processes matter more than tools", "Other"], "default": ["Tech will stay", "Processes matter more than tools"], "optional": False, "store_to": "domain.ai.theses", "max_select": 3, "other_option": "Other", "other_placeholder": "Write your thesis"},
    {"id": 44, "question": "1–2 signature lines", "ui_type": "text_optional", "options": [], "default": "", "optional": True, "store_to": "domain.ai.signature_lines_optional"},
    {"id": 45, "question": "Startup life theses (select up to 2)", "ui_type": "checkbox", "options": ["No gloss, it's hard", "Iterations solve", "Sales matter more than product", "Team breaks/builds", "Focus matters more than ideas", "Other"], "default": ["Iterations solve"], "optional": True, "store_to": "domain.startups.theses", "max_select": 2, "other_option": "Other", "other_placeholder": "Write your thesis", "followup_fields": [{"store_to": "domain.startups.details", "label": "More about startups", "placeholder": "Your experience, cases, takeaways", "optional": True}]},
    {"id": 46, "question": "Work and boundaries", "ui_type": "radio", "options": ["I work a lot", "I'm for balance", "Results matter, but no burnout", "Depends on stage"], "default": "Results matter, but no burnout", "optional": True, "store_to": "domain.career.boundaries"},
    {"id": 47, "question": "Humor level 1–10", "ui_type": "slider", "options": [1, 10], "default": 4, "optional": False, "store_to": "style.humor_level", "slider_labels": {"min": "Almost no humor", "max": "Lots of humor"}},
    {"id": 48, "question": "What can't you joke about?", "ui_type": "checkbox", "options": ["Illness/disability", "Religion", "Politics", "Race/ethnicity", "Appearance", "Other", "No limits"], "default": ["Illness/disability", "Religion", "Politics", "Race/ethnicity"], "optional": False, "store_to": "safety.humor_taboo", "other_option": "Other", "other_placeholder": "Write topic", "exclusive_option": "No limits"},
    {"id": 49, "question": "Humor is mostly about…", "ui_type": "radio", "options": ["Self-deprecation", "Industry", "Life", "Sarcastic tease", "Almost never joke"], "default": "Industry", "optional": False, "store_to": "style.humor_target"},
    {"id": 50, "question": "1 example joke/tease", "ui_type": "text_optional", "options": [], "default": "", "optional": True, "store_to": "style.joke_example_optional"},
    {"id": 51, "question": "«One truth about life» (select)", "ui_type": "radio", "options": ["Must keep growing", "Discipline beats motivation", "People decide", "Health decides", "Freedom through responsibility"], "default": "Discipline beats motivation", "optional": True, "store_to": "worldview.life_truth"},
    {"id": 52, "question": "«Doing well in life» for you is…", "ui_type": "checkbox", "options": ["Time freedom", "Money", "Family", "Health", "Interest in life", "Impact/contribution", "Other"], "default": ["Time freedom", "Family"], "optional": True, "store_to": "worldview.doing_well", "other_option": "Other", "other_placeholder": "Elaborate", "followup_fields": [{"store_to": "worldview.doing_well_other", "label": "What else matters?", "placeholder": "Your own words", "optional": True}]},
    {"id": 53, "question": "Friendship/relationships and boundaries", "ui_type": "radio", "options": ["I'm for a close circle", "I'm about «partnership», not friendship", "I connect easily", "Don't want to write about it"], "default": "I'm for a close circle", "optional": True, "store_to": "worldview.relationships"},
    {"id": 54, "question": "Write 1 example of how you answer a personal question (1–2 sentences)", "ui_type": "text_optional", "options": [], "default": "e.g. «Yes, I have two kids — that really shifts priorities»", "optional": True, "store_to": "worldview.short_answer_optional"},
    {"id": 55, "question": "When a debate heats up, you…", "ui_type": "radio", "options": ["Lower tone and clarify facts", "Joke and ease tension", "End the dialogue", "Respond firmer"], "default": "Lower tone and clarify facts", "optional": False, "store_to": "debate.deescalation"},
    {"id": 56, "question": "«I agree and add» (select 2 templates)", "ui_type": "checkbox", "options": ["Yes, and here's what matters…", "Agree, but there's a nuance…", "Right. I'd add…", "100%. Plus…", "Same essence, but…", "Other"], "default": ["Agree, but there's a nuance…", "Right. I'd add…"], "optional": True, "store_to": "debate.agree_add_templates", "max_select": 2, "other_option": "Other", "other_placeholder": "Write your template"},
    {"id": 57, "question": "You mostly debate about…", "ui_type": "radio", "options": ["AI", "Startups", "Marketing", "Ops/processes", "Logistics", "Rarely debate", "Other"], "default": "AI", "optional": False, "store_to": "debate.common_topic", "other_option": "Other", "other_placeholder": "Specify"},
    {"id": 58, "question": "Argument style in debate", "ui_type": "radio", "options": ["Facts/numbers", "Practice/cases", "Logic/cause-effect", "Lead to point with questions"], "default": "Logic/cause-effect", "optional": False, "store_to": "debate.argument_style"},
    {"id": 59, "question": "Select 5 «building blocks» (ready phrases)", "ui_type": "checkbox", "options": ["Look, the key here is…", "To be honest…", "In fact…", "The problem isn't …, it's …", "Quick check: …", "This is solved by process/system", "Let's simplify: …", "Question: …", "I'd do it like this: …", "Agree, but there's a nuance…", "Other"], "default": ["Look, the key here is…", "In fact…", "Question: …", "Let's simplify: …", "This is solved by process/system"], "optional": True, "store_to": "style.bricks_selected", "max_select": 5, "other_option": "Other", "other_placeholder": "Write your phrase"},
    {"id": 60, "question": "Banned phrases (select up to 5)", "ui_type": "checkbox", "options": ["Great post", "Love this", "So true", "It's worth noting", "In the end", "In today's world", "Let's unpack", "First/secondly", "Other"], "default": ["Great post", "Love this", "It's worth noting", "In the end", "Let's unpack"], "optional": True, "store_to": "anti_ai.banned_phrases_extra", "max_select": 5, "other_option": "Other", "other_placeholder": "Write phrase"},
    {"id": 61, "question": "When someone's struggling, you…", "ui_type": "radio", "options": ["Listen and give short advice", "Support without advice", "Give a practical step", "Don't comment on such topics"], "default": "Give a practical step", "optional": False, "store_to": "interaction.support_style"},
    {"id": 62, "question": "How do you avoid invalidating?", "ui_type": "radio", "options": ["Acknowledge difficulty and give a step", "Highlight progress", "Speak directly but respectfully"], "default": "Acknowledge difficulty and give a step", "optional": False, "store_to": "interaction.validation_style"},
    {"id": 63, "question": "How do you gently disagree and add nuance?", "ui_type": "radio", "options": ["With a question", "With a counterexample", "With nuance", "With mini-advice"], "default": "With a question", "optional": False, "store_to": "interaction.challenge_style"},
    {"id": 64, "question": "Response to toxic phrasing (select strategy)", "ui_type": "radio", "options": ["Translate to facts", "Set boundary and exit", "Calmly state it's unacceptable", "Ignore"], "default": "Calmly state it's unacceptable", "optional": False, "store_to": "safety.toxic_handling"},
    {"id": 65, "question": "5 mandatory rules for your text (select 5)", "ui_type": "checkbox", "options": ["Always 1 concrete from post", "One point, no fluff", "No corporate speak", "No motivational clichés", "Question at end (when appropriate)", "No made-up personal experience", "Friendly but to the point", "Light sarcasm OK, no toxicity", "Don't touch taboo topics"], "default": ["Always 1 concrete from post", "One point, no fluff", "No corporate speak", "No made-up personal experience", "Don't touch taboo topics"], "optional": False, "store_to": "rules.mandatory", "max_select": 5},
]

QUESTIONS_BY_ID_EN = {q["id"]: q for q in ONBOARDING_QUESTIONS_EN}

EXTRA_QUESTIONS_EN = [
    {"id": "roughness", "question": "Anti-AI «roughness» 1–10", "ui_type": "slider", "options": [1, 10], "default": 6, "optional": False, "store_to": "anti_ai.roughness", "slider_labels": {"min": "Smooth, polished", "max": "Human, alive"}},
]
